# EMBEDDED SERVER CONFIGURATION
server:
    port: ${port:8086}
    context-path: /
    error.whitelabel.enabled: false
    compression:
      enabled: true
      min-response-size: 1024
      mime-types:
          - text/html
          - text/css
          - text/plain
          - text/xml
          - application/json
          - application/javascript


spring:
  profiles: dev

price:
    restUrl: https://forms-dev/int2/GetPriceSvc

